### ISSUE TITLE
Approach to Geometry

### ISSUE THREAD

**Issue by SchrodingersGat** [andromeda-cad/andromeda-rfcs#8]
This is simply for discussion, not ready to be an RFC yet.

One of the current drawbacks of KiCad is the haphazard way that various geometry tools are implemented (or unimplemented). There are inconsistencies between the various views, and the drawing tools that are present are awkward. 
### Line Ends

Line segments and arc should lock-on to line ends, rather than looking "close enough" but not actually connected.

This could be improved by having more complicated models behind the scenes.
### Polygons

In eeschema, polygons can be edited by dragging nodes around (although this requires a weird keypress, and is somewhat non-obvious). You can add nodes fairly simply, and the line segments remain joined as you move node around.

In pcbnew, polygons are simply line segments that get drawn in sequence, but there are no rules actually joining them together. If you subsequently move one line segment, then it is harshly abandoned by its line parents, to survive in the wild, untethered from reality. 

This is particularly annoying when you are creating the board outline, which MUST be a closed shape.
### Arcs

eeschema and pcbnew both find unique ways of making arc drawing clunky. There should be a way of defining arcs by centre,point,point and also by point,point,point. 

Additionally, whenever an arc is created that is **not** aligned on a simple x,y plane, then it is ridiculously tedious to make this connect with a line endpoint. (This is really more of a UI issue than an issue with the underlying graphic primitives).
### Lack of Editing Tools

Many graphical primitives in KiCad  are vary hard to edit "after the fact" - and the tools available are not consistent between views.
## Geometry Strategies

There are a number of approaches that can be taken with regard to graphical objects:
### Separate Simple Primitives

Each graphical "construct" (be it a pad, symbol, board outline, etc) is constructed of unique, simple graphical primitives (such as straight lines, arcs). Each view (schematic, pcb) would need to look at each primitive, and determine if (for e.g.) a set of lines actually form a polygon. This is, generally speaking, the way that KiCad handles graphics - just blit items on top of each other to create (the illusion of) more complex shapes.

**Advantages**
- Can define many arbitrary segments at will
- Simpler file serialization
- Able to define complex PCB shapes by combining lines and arcs

**Disadvantages**
- Less powerful toolset, tedious to edit complex shapes
- Each segment has to be checked against every other line segment to create complex geometric models
- Parts must be "assembled" from scratch each time the object is loaded from a file
- Segment association is highly dependent on nodes being in _exactly_ the same spot - many errors in KiCad caused by lines almost touching but not quite.
### Polylines and Arcs

Most shapes can be defined by polylines and arcs. Polylines can be closed and filled to create polygons, arcs can be closed to create circles. There are powerful polygon libs available via boost for performing boolean operations, detecting collisions, etc.

**Advantages**
- Relational shapes can be updated easier
- Fewer points to save in external file
- Comprehensive tools for polygon operations exist

**Disadvantages**
- How to make complex shapes that include both straight lines and curves?
- (e.g. how to make a board outline with rounded corners?)
- Slightly more complicated to store / load
### Segment Paths

Another option is to define shapes using path segments that can be curved or straight, which can be used to define lines, arcs, circles, polygons, and complex combinations of any of these.

![complex](https://cloud.githubusercontent.com/assets/10080325/19109900/1a7bb684-8b43-11e6-9ddf-a60cc843cc35.png)

**Advantages**
- Simple set of primitives combined into complex shapes
- Shapes with internal models can be edited / updated 
- Easy definition of (for e.g.) roundrect pads with 4 segments

**Disadvantages**
- Polygon rules don't apply to arcs, and more complicated to detect intersections, boolean operations, etc (would this require extra libs to be written?)
- Harder to render than individual graphical constructs
## Qt Features

Qt has reasonably complex graphics tools.

[QPainterPath](http://doc.qt.io/qt-5/qpainterpath.html) provides drawing of arbitrary paths with straight lines curves

[QPolygon](http://doc.qt.io/qt-4.8/qpolygon.html) provides for drawing polygons (with some simple boolean operations available)
## Feedback

What do we think? I think it is important to develop a suite of geometry tools that cover symbols, schematics, footprints, and pcb layout. These should include functions to check for intersection / collision, and intelligently edit shapes on the fly.

In particular, geometric functions are required for defining and testing intersection of copper zones, keepout zones, board outline and cutouts, etc etc

**Comment by iromero91** [comment]
I propose using DXF [LWPOLYLINE](http://www.autodesk.com/techpubs/autocad/acad2000/dxf/lwpolyline_dxf_06.htm)s wherever it makes sense, they are basically a list of segments and arcs, arcs are represented as segments with a "[bulge](http://www.afralisp.net/autolisp/tutorials/polyline-bulges-part-1.php)" parameter, it may seem a bit confusing at first but it keeps the representation compact. In memory the lwpolyline can be deconstructed as segments and arcs for the purposes of editing.

**Comment by SchrodingersGat** [comment]
@iromero91 this concept is very good. I tend to agree that a LWPOLYLINE (or whatever our equivalent is) is enough to encode all shapes we would be interested in. It should also make DXF exporting a breeze as we conform (or close enough) to the standard
